name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: gemfury
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: javascript
    steps:
      - uses: actions/checkout@v3
      - name: Configure Environment Variables
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          VERSION=${TAG_NAME#"v"}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          node-version-file: javascript/.nvmrc
      - run: yarn install --immutable
      - run: yarn generate
      - run: |
          yarn config set npmAlwaysAuth true &&
          yarn config set npmAuthToken "$FURY_TOKEN"
        shell: bash
        env:
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
      - name: Configure Version
        run: |
          sed -i -e 's/"version": "0.0.0"/"version": "'"$VERSION"'"/' package.json
      - run: yarn npm publish
